name: Windows Node.js Example with Local nvm.exe
on: [push]

jobs:
  web-build:    
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with: 
        ref: main
        submodules: true
        sparse-checkout: |
          subrepos/WebPlugins/src/front-end

    - name: Install NVM 
      shell: powershell
      run: |
        ls
        cd .\subrepos\WebPlugins\src\front-end
        ls
        .\nvm-setup.exe /S
        
    - name: Set NVM To PATH
      run: |
        $nvmPath = "$env:USERPROFILE\.nvm"
        $npmPath = "$env:USERPROFILE\.nvm\npm"
        $env:Path = "$nvmPath;$npmPath;$env:Path"
        Set-Item -Path Env:Path -Value $env:Path

    - name: Verify NVM Installation
      shell: cmd
      run: |
        nvm --version

    - name: Install Node.js
      shell: cmd
      run: |
        nvm install 14.21.3
        nvm use 14.21.3
        node -v

    - name: Install Dependencies
      run: npm install
      
    - name: Npm Test
      run: npm test

    - name: Build Project
      run: |
        ls
        cd packages\IoTCenterWebPlugin
        npm run build