name: Windows Node.js Example with Local nvm.exe
on: [push]

jobs:
  web-build:    
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with: 
        ref: main
        submodules: true
        sparse-checkout: |          
          subrepos/WebPlugins

    - name: Install NVM 
      shell: powershell
      run: |
        ls
        cd .\subrepos\WebPlugins\src\front-end
        ls
        .\nvm-setup.exe /S
        
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
            
        nvm version

    - name: Verify NVM Installation
      shell: cmd
      run: |
        nvm --version

    - name: Install Node.js
      shell: cmd
      run: |
        nvm install 14.21.3
        nvm use 14.21.3
        node -v

    - name: Install Dependencies
      run: npm install
      
    - name: Build Project
      run: |
        cd packages\IoTCenterWebPlugin
        npm run build