name: Build and Release

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Set output for artifact name
        id: set-artifact-name
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "artifact_name=Windows.zip" >> $GITHUB_ENV
            echo "archive_ext=zip" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            echo "artifact_name=Linux_x86_x64.tar.gz" >> $GITHUB_ENV
            echo "archive_ext=tar.gz" >> $GITHUB_ENV
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            echo "artifact_name=MacOsxArm64.tar.gz" >> $GITHUB_ENV
            echo "archive_ext=tar.gz" >> $GITHUB_ENV
          else
            echo "artifact_name=${{ runner.os }}_${{ runner.arch }}_${{ github.ref_name }}_release.zip" >> $GITHUB_ENV
            echo "archive_ext=zip" >> $GITHUB_ENV
          fi
        shell: bash

      - name : out
        run: |
          echo  ${{ env.artifact_name }}
          echo ${{ env.archive_ext }}