name: Sync To Gitee

on: push

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@v1.5
      with:
        src: github/JJ053
        dst: gitee/GW_zhonglijun
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "Toms_Test"