name: Web Build and Release1
on:
  push:
  
jobs:
  web-build:
    
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with: 
        ref: main
        submodules: recursive
        sparse-checkout: |
          subrepos/WebPlugins/src/front-end/packages/IoTCenterWebBase

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '23.1.0'

    - name: Install pnpm
      run: |
        npm --version

        npm install pnpm -g
        
        pnpm --version
        ls
        cd ./subrepos/WebPlugins/src/front-end/packages/IoTCenterWebBase
        pnpm install 
        ls
        tree
        pnpm build
      shell: pwsh

